export const API = {
  AUTH_REFRESH: '/auth/refresh',
  AUTH_ME: '/auth/me',
  AUTH_LOGIN: '/auth/login',
  AUTH_REGISTER: '/auth/register',
  AUTH_LOGOUT: '/auth/logout',
  AUTH_SESSIONS: '/auth/sessions',
  AUTH_EMAIL_SEND_CODE: '/auth/email/send-code',
  AUTH_EMAIL_LOGIN: '/auth/email/login',
  AUTH_EMAIL_RESET_PASSWORD: '/auth/email/reset-password',
  USER_HEARTBEAT: '/user/heartbeat',
  USER_ME: '/user/me',
  USER_PROFILE_UPDATE: '/user/me/profile',
  BLOG_DASHBOARD: '/blog/dashboard',
  BLOG_SUMMARY: '/blog/summary',
  POSTS_LIST: '/posts',
  TAGS_LIST: '/tags',
  TAGS_CREATE: '/tags',
  CATEGORIES_LIST: '/categories',
  ANNOUNCEMENT_ACTIVE: '/announcement/active',
  OAUTH_GITHUB_BIND: '/auth/oauth/github/bind',
  USER_EMAIL_SEND_CODE: '/user/me/email/send-code',
  USER_EMAIL_UPDATE: '/user/me/email',
  USER_LAYOUT: '/user-layout',
  COMMENTS_PAGE: '/comments/page',
  COMMENTS_REPLY_PAGE: '/comments/replyPage',
  COMMENTS_CREATE: '/comments',
  COMMENTS_EDIT: (id: number) => `/comments/${id}`,
  COMMENTS_DELETE: (id: number) => `/comments/${id}`,
  COMMENTS_LIKE: (id: number) => `/comments/${id}/like`,
  COMMENTS_LIKED: '/comments/liked',
  COMMENTS_REPORT: (id: number) => `/comments/${id}/report`,
  USER_BRIEF: (id: string) => `/users/${id}/brief`,
  NOTIFICATION_LIST: '/notification/me',
  NOTIFICATION_SUMMARY: '/notification/me/summary',
  NOTIFICATION_READ_ALL: '/notification/read-all',
  NOTIFICATION_READ: (id: number) => `/notification/${id}/read`,
  PERMISSION_REQUESTS: '/permission-request',
  PERMISSION_REQUESTS_ME: '/permission-request/me',
  PERMISSION_REQUEST_APPROVE: (id: number) => `/permission-request/${id}/approve`,
  PERMISSION_REQUEST_REJECT: (id: number) => `/permission-request/${id}/reject`,
  DISCOVERIES: '/discoveries',
  DISCOVERIES_ALL: '/discoveries/all',
  DISCOVERIES_SEND_CODE: '/discoveries/send-code',
  DISCOVER_CHECK: (id: number) => `/discoveries/${id}/check`,
  POSTS_STATS: '/post-stats',
} as const;
