export type EditorTheme = 'light' | 'dark';

export interface PreviewThemeConfig {
  id: string;
  label: string;
  dark: boolean;
  codeTheme: string;
  mermaidTheme: 'default' | 'dark';
  vars: Record<string, string>;
}

export const REQUIRED_PREVIEW_VARS = [
  '--me-text',
  '--me-text-secondary',
  '--me-text-muted',
  '--me-text-tertiary',
  '--me-border',
  '--me-bg',
  '--me-bg-soft',
  '--me-bg-code',
  '--me-bg-highlight',
  '--me-primary',
  '--me-link',
  '--me-success',
  '--me-warning',
  '--me-danger',
  '--me-info',
  '--me-bg-success',
  '--me-bg-warning',
  '--me-bg-danger',
  '--me-bg-info',
  '--me-error',
] as const;

export const PREVIEW_THEMES: PreviewThemeConfig[] = [
  {
    id: 'github-light',
    label: 'GitHub Light',
    dark: false,
    codeTheme: 'github-light',
    mermaidTheme: 'default',
    vars: {
      '--me-text': '#1f2328',
      '--me-text-secondary': '#57606a',
      '--me-text-muted': '#8c959f',
      '--me-text-tertiary': '#6e7781',
      '--me-border': '#d0d7de',
      '--me-bg': '#ffffff',
      '--me-bg-soft': '#f6f8fa',
      '--me-bg-code': '#f6f8fa',
      '--me-bg-highlight': 'rgba(59, 130, 246, 0.15)',
      '--me-primary': '#0969da',
      '--me-link': '#0969da',
      '--me-success': '#1a7f37',
      '--me-warning': '#9a6700',
      '--me-danger': '#cf222e',
      '--me-info': '#0969da',
      '--me-bg-success': '#dafbe1',
      '--me-bg-warning': '#fff8c5',
      '--me-bg-danger': '#ffebe9',
      '--me-bg-info': '#ddf4ff',
      '--me-error': '#cf222e',
    },
  },
  {
    id: 'github-dark',
    label: 'GitHub Dark',
    dark: true,
    codeTheme: 'github-dark',
    mermaidTheme: 'dark',
    vars: {
      '--me-text': '#e6edf3',
      '--me-text-secondary': '#9198a1',
      '--me-text-muted': '#6e7681',
      '--me-text-tertiary': '#8b949e',
      '--me-border': '#30363d',
      '--me-bg': '#0d1117',
      '--me-bg-soft': '#161b22',
      '--me-bg-code': '#161b22',
      '--me-bg-highlight': 'rgba(88, 166, 255, 0.15)',
      '--me-primary': '#4493f8',
      '--me-link': '#4493f8',
      '--me-success': '#3fb950',
      '--me-warning': '#d29922',
      '--me-danger': '#f85149',
      '--me-info': '#4493f8',
      '--me-bg-success': 'rgba(46, 160, 67, 0.15)',
      '--me-bg-warning': 'rgba(187, 128, 9, 0.15)',
      '--me-bg-danger': 'rgba(248, 81, 73, 0.1)',
      '--me-bg-info': 'rgba(56, 139, 253, 0.15)',
      '--me-error': '#f85149',
    },
  },
  {
    id: 'min-light',
    label: 'Min Light',
    dark: false,
    codeTheme: 'min-light',
    mermaidTheme: 'default',
    vars: {
      '--me-text': '#24292e',
      '--me-text-secondary': '#57606a',
      '--me-text-muted': '#8c959f',
      '--me-text-tertiary': '#6e7781',
      '--me-border': '#e1e4e8',
      '--me-bg': '#ffffff',
      '--me-bg-soft': '#f6f8fa',
      '--me-bg-code': '#f6f8fa',
      '--me-bg-highlight': 'rgba(9, 105, 218, 0.12)',
      '--me-primary': '#0366d6',
      '--me-link': '#0366d6',
      '--me-success': '#22863a',
      '--me-warning': '#b08800',
      '--me-danger': '#d73a49',
      '--me-info': '#0366d6',
      '--me-bg-success': '#f0fff4',
      '--me-bg-warning': '#fff8c5',
      '--me-bg-danger': '#ffeef0',
      '--me-bg-info': '#f1f8ff',
      '--me-error': '#d73a49',
    },
  },
  {
    id: 'min-dark',
    label: 'Min Dark',
    dark: true,
    codeTheme: 'min-dark',
    mermaidTheme: 'dark',
    vars: {
      '--me-text': '#c9d1d9',
      '--me-text-secondary': '#8b949e',
      '--me-text-muted': '#6e7681',
      '--me-text-tertiary': '#8b949e',
      '--me-border': '#30363d',
      '--me-bg': '#0d1117',
      '--me-bg-soft': '#161b22',
      '--me-bg-code': '#161b22',
      '--me-bg-highlight': 'rgba(56, 139, 253, 0.15)',
      '--me-primary': '#58a6ff',
      '--me-link': '#58a6ff',
      '--me-success': '#7ee787',
      '--me-warning': '#d29922',
      '--me-danger': '#ff7b72',
      '--me-info': '#58a6ff',
      '--me-bg-success': 'rgba(46, 160, 67, 0.15)',
      '--me-bg-warning': 'rgba(187, 128, 9, 0.15)',
      '--me-bg-danger': 'rgba(248, 81, 73, 0.1)',
      '--me-bg-info': 'rgba(56, 139, 253, 0.15)',
      '--me-error': '#ff7b72',
    },
  },
  {
    id: 'nord',
    label: 'Nord',
    dark: true,
    codeTheme: 'nord',
    mermaidTheme: 'dark',
    vars: {
      '--me-text': '#d8dee9',
      '--me-text-secondary': '#81a1c1',
      '--me-text-muted': '#4c566a',
      '--me-text-tertiary': '#88c0d0',
      '--me-border': '#3b4252',
      '--me-bg': '#2e3440',
      '--me-bg-soft': '#3b4252',
      '--me-bg-code': '#2e3440',
      '--me-bg-highlight': 'rgba(136, 192, 208, 0.15)',
      '--me-primary': '#88c0d0',
      '--me-link': '#81a1c1',
      '--me-success': '#a3be8c',
      '--me-warning': '#ebcb8b',
      '--me-danger': '#bf616a',
      '--me-info': '#81a1c1',
      '--me-bg-success': 'rgba(163, 190, 140, 0.15)',
      '--me-bg-warning': 'rgba(235, 203, 139, 0.15)',
      '--me-bg-danger': 'rgba(191, 97, 106, 0.15)',
      '--me-bg-info': 'rgba(129, 161, 193, 0.15)',
      '--me-error': '#bf616a',
    },
  },
  {
    id: 'tokyo-night',
    label: 'Tokyo Night',
    dark: true,
    codeTheme: 'tokyo-night',
    mermaidTheme: 'dark',
    vars: {
      '--me-text': '#c0caf5',
      '--me-text-secondary': '#a9b1d6',
      '--me-text-muted': '#565f89',
      '--me-text-tertiary': '#9aa5ce',
      '--me-border': '#292e42',
      '--me-bg': '#1a1b26',
      '--me-bg-soft': '#24283b',
      '--me-bg-code': '#16161e',
      '--me-bg-highlight': 'rgba(122, 162, 247, 0.15)',
      '--me-primary': '#7aa2f7',
      '--me-link': '#7aa2f7',
      '--me-success': '#9ece6a',
      '--me-warning': '#e0af68',
      '--me-danger': '#f7768e',
      '--me-info': '#7dcfff',
      '--me-bg-success': 'rgba(158, 206, 106, 0.15)',
      '--me-bg-warning': 'rgba(224, 175, 104, 0.15)',
      '--me-bg-danger': 'rgba(247, 118, 142, 0.15)',
      '--me-bg-info': 'rgba(125, 207, 255, 0.15)',
      '--me-error': '#f7768e',
    },
  },
];

export const DEFAULT_PREVIEW_THEME = 'github-light';

export const EDITOR_THEMES: EditorTheme[] = ['light', 'dark'];

export function getPreviewTheme(id: string): PreviewThemeConfig {
  return PREVIEW_THEMES.find((t) => t.id === id) ?? PREVIEW_THEMES[0];
}

export function applyPreviewTheme(el: HTMLElement, theme: PreviewThemeConfig): void {
  for (const [key, value] of Object.entries(theme.vars)) {
    el.style.setProperty(key, value);
  }
}
